
from tkinter import *
import tkinter as tk

mc_list = {
    1: {
        'id': 'MM32f003NW',
        'processor': 'ARM Cortex M0',
        'frequency': '48',
        'flash': '16',
        'ram': '2',
        "gpio": "16",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "8x12bit",
        "eeprom": "0",
        "pack": "QFN20",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""

    },
    2: {
        "id": "MM32f003TW",
        "processor": "ARM Cortex M0",
        "frequency": "48",
        "flash": "16",
        "ram": "2",
        "gpio": "16",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "-",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "8x12bit",
        "eeprom": "0",
        "pack": "TSSOP20",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    ###############################################################
    # MM32f031 controller starte
    ###################################################################
    3: {
        "id": "MM32F031F4P6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "16",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "-",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "9x12bit",
        "eeprom": "",
        "pack": "TSSOP20",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    4: {
        "id": "MM32F031F4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "16",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "9x12bit",
        "eeprom": "",
        "pack": "QFN20",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    5: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    6: {
        "id": "MM32f031K4T6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "25",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "-",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "-",
        "pack": "LQFP32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    7: {
        "id": "MM32f031C4T6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "39",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    8: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    9: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    10: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    11: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    12: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    13: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    14: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    15: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    16: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    17: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    18: {
        "id": "MM32f031K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    ############################################################################
    ##------------------MM32F032-----
    ##-------------total 8 controllers available------
    #############################################################################
    19: {
        "id": "MM32f032K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    20: {
        "id": "MM32f032K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    21: {
        "id": "MM32f032K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    22: {
        "id": "MM32f032K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    23: {
        "id": "MM32f032K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    24: {
        "id": "MM32f032K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    25: {
        "id": "MM32f032K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    26: {
        "id": "MM32f032K4U6",
        "processor": "ARM Cortex M0",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    #########################################################
    ##------------------------MM32F103---cortext-m3
    ##
    ########################################################
    27: {
        "id": "MM32f103K4U6",
        "processor": "ARM Cortex M3",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    28: {
        "id": "MM32F103K4U6",
        "processor": "ARM Cortex M3",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    29: {
        "id": "MM32F103K4U6",
        "processor": "ARM Cortex M3",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    },
    30: {
        "id": "MM32F103K4U6",
        "processor": "ARM Cortex M3",
        "frequency": "72",
        "flash": "16",
        "ram": "4",
        "gpio": "27",
        "adv_tm": "1",
        "gptm": "5",
        "wdg": "2",
        "rtc": "",
        "uart": "1",
        "i2c": "1",
        "spi": "1",
        "adc": "10x12bit",
        "eeprom": "",
        "pack": "QFN32",
        "dac": "",
        "usb": "",
        "can": "",
        "sdio": "",
        "comp": "",
        "aes": "",
        "trng": ""
    }

}

def micro_controller_details():
    row_items = 5
    d = 1
    for i in range(0, 30):
        microcontroller = Label(master, text=mc_list[d]['id'], bg="#142E54", fg="white", font="Lato 8 bold",
                                padx="5", pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=0,
                                                                                         sticky=N + S + E + W)
        processor = Label(master, text=mc_list[d]['processor'], bg="#142E54", fg="white", font="Lato 8 bold",
                          padx="5", pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=1,
                                                                                   sticky=N + S + E + W)
        frequency = Label(master, text=mc_list[d]['frequency'], bg="#142E54", fg="white", font="Lato 8 bold",
                          padx="5", pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=2,
                                                                                   sticky=N + S + E + W)
        flash = Label(master, text=mc_list[d]["flash"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                      pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=3, sticky=N + S + E + W)
        ram = Label(master, text=mc_list[d]["ram"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=4, sticky=N + S + E + W)
        gpio = Label(master, text=mc_list[d]["gpio"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                     pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=5, sticky=N + S + E + W)
        adv_tm = Label(master, text=mc_list[d]["adv_tm"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                       pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=6, sticky=N + S + E + W)
        gptm = Label(master, text=mc_list[d]["gptm"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                     pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=7, sticky=N + S + E + W)
        wdg = Label(master, text=mc_list[d]["wdg"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=8, sticky=N + S + E + W)
        rtc = Label(master, text=mc_list[d]["rtc"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=9, sticky=N + S + E + W)
        uart = Label(master, text=mc_list[d]["uart"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                     pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=10, sticky=N + S + E + W)
        i2c = Label(master, text=mc_list[d]["i2c"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=11, sticky=N + S + E + W)
        spi = Label(master, text=mc_list[d]["spi"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=12, sticky=N + S + E + W)
        adc = Label(master, text=mc_list[d]["adc"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=13, sticky=N + S + E + W)
        eeprom = Label(master, text=mc_list[d]["eeprom"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                       pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=14,
                                                                      sticky=N + S + E + W)
        pack = Label(master, text=mc_list[d]["pack"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                     pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=15, sticky=N + S + E + W)
        dac = Label(master, text=mc_list[d]["dac"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=16, sticky=N + S + E + W)
        usb = Label(master, text=mc_list[d]["usb"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=17, sticky=N + S + E + W)
        can = Label(master, text=mc_list[d]["can"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=18, sticky=N + S + E + W)
        sdio = Label(master, text=mc_list[d]["sdio"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                     pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=19, sticky=N + S + E + W)
        comp = Label(master, text=mc_list[d]["comp"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                     pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=20, sticky=N + S + E + W)
        aes = Label(master, text=mc_list[d]["aes"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                    pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=21, sticky=N + S + E + W)
        trng = Label(master, text=mc_list[d]["trng"], bg="#142E54", fg="white", font="Lato 8 bold", padx="5",
                     pady="5", borderwidth=2, relief="groove").grid(row=row_items, column=22, sticky=N + S + E + W)
        row_items = row_items + 1
        d = d + 1


master= Tk()
master.title("My First GUI")
master.geometry("800x200")
frame1=Frame(master)
frame1.grid()
label1 = Label(frame1, text = "Here is a label!")
label1.grid()
button1 = Button(frame1, text = "I am a Button")
button1.grid()
micro_controller_details()



text1 = Text(frame1, width = 35, height = 5)
text1.grid()
radiobutton1 = Radiobutton(frame1, text= "C Programming", value=0)
radiobutton1.grid()
radiobutton2 =Radiobutton(frame1, text= "Python Programming")
radiobutton2.grid()
master.mainloop()